<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>ControlLoterias</AssemblyName>
    <RootNamespace>LoteriaTwo</RootNamespace>
    <Product>Control de Loterías</Product>
    <ApplicationIcon>Sin-título-1.ico</ApplicationIcon>
  </PropertyGroup>


  <ItemGroup>
    <Content Include="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sin-título-1.ico" />
    <Content Include="unreal_prado.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="unreal_torre.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
